### ISSUE TITLE
UnboundLocalError: local variable 'ln' referenced before assignment

### ISSUE THREAD

**Issue by LittleTerry** [magnusjwatson2786/SRT-Audio#1]
I use Windows, and I replace the values for srtpath and sppath variables in the tts.py file and then run “python tts.py”.
But it turns out as follows:

Traceback (most recent call last):
  File "tts.py", line 9, in <module>
    parsesrt.parse(srtpath)
  File "D:\SRT-Audio-master\parsesrt.py", line 22, in parse
    ln+=b" "
UnboundLocalError: local variable 'ln' referenced before assignment

**Comment by waxweb** [comment]
exactly my problem, could a max/linux person help?

**Comment by magnusjwatson2786** [comment]
Yeah, sorry about that. I forgot to declare the variable before using it. Fixed it now. Should work fine.
