### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by waxweb** [magnusjwatson2786/SRT-Audio#2]
when I try to install the requirements, I get:
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from versions: 302, 303)
I am on Python 3.10 on Windows 10 64... do I need to do something like make a specific 32 bit install of Python, or something like that? Please help :)

**Comment by waxweb** [comment]
ok! I downgraded to 3.9, in which pywin32 still works.
I seem to have a noob directory problem, being on windows and all: 
I double \\'d the directory when inserting it in tts.py, but get:

i run tts.py and get
X:\01____PORTABLE\speech_pytts\SRT-Audio>python tts.py
Traceback (most recent call last):
  File "X:\01____PORTABLE\speech_pytts\SRT-Audio\tts.py", line 8, in <module>
    parsesrt.parse(srtpath)
  File "X:\01____PORTABLE\speech_pytts\SRT-Audio\parsesrt.py", line 22, in parse
    ln+=b" "
UnboundLocalError: local variable 'ln' referenced before assignment

what to do?

**Comment by magnusjwatson2786** [comment]
Sorry about that. I just fixed it. It should work fine now.

**Comment by waxweb** [comment]
thank you for the help :)

I'm still having version problems with python and requirements...
immediately there is a pywintypes error [ImportError: No system module 
'pywintypes' (pywintypes38.dll)], which should be in pywin32..

could I ask you exactly what version of python you are using, and if I 
should set any specific version of pywin32 in the requirements?

Thank you! I am very eager to try this...

here is the full error:


Traceback (most recent call last):
   File "tts.py", line 12, in <module>
     engine = pyttsx3.init()
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\__init__.py", 
line 22, in init
     eng = Engine(driverName, debug)
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\engine.py", 
line 30, in __init__
     self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, 
debug)
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\driver.py", 
line 50, in __init__
     self._module = importlib.import_module(name)
   File 
"C:\Users\David\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", 
line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in 
_find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 783, in 
exec_module
   File "<frozen importlib._bootstrap>", line 219, in 
_call_with_frames_removed
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\drivers\sapi5.py", 
line 10, in <module>
     import pythoncom
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pythoncom.py", 
line 2, in <module>
     import pywintypes
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", 
line 105, in <module>
     __import_pywin32_system_module__("pywintypes", globals())
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", 
line 87, in __import_pywin32_system_module__
     raise ImportError("No system module '%s' (%s)" % (modname, 
filename))
ImportError: No system module 'pywintypes' (pywintypes38.dll)
