### ISSUE TITLE
No system module 'pywintypes' (pywintypes38.dll)

### ISSUE THREAD

**Issue by magnusjwatson2786** [magnusjwatson2786/SRT-Audio#3]
Refrencing issue pointed out by @waxweb

I'm still having version problems with python and requirements...
immediately there is a pywintypes error [ImportError: No system module 
'pywintypes' (pywintypes38.dll)], which should be in pywin32..

could I ask you exactly what version of python you are using, and if I 
should set any specific version of pywin32 in the requirements?

Thank you! I am very eager to try this...

here is the full error:

Traceback (most recent call last):
   File "tts.py", line 12, in <module>
     engine = pyttsx3.init()
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\__init__.py", 
line 22, in init
     eng = Engine(driverName, debug)
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\engine.py", 
line 30, in __init__
     self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, 
debug)
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\driver.py", 
line 50, in __init__
     self._module = importlib.import_module(name)
   File 
"C:\Users\David\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", 
line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in 
_find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 783, in 
exec_module
   File "<frozen importlib._bootstrap>", line 219, in 
_call_with_frames_removed
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pyttsx3\drivers\sapi5.py", 
line 10, in <module>
     import pythoncom
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pythoncom.py", 
line 2, in <module>
     import pywintypes
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", 
line 105, in <module>
     __import_pywin32_system_module__("pywintypes", globals())
   File 
"C:\Users\David\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", 
line 87, in __import_pywin32_system_module__
     raise ImportError("No system module '%s' (%s)" % (modname, 
filename))
ImportError: No system module 'pywintypes' (pywintypes38.dll)

_Originally posted by @waxweb in https://github.com/magnusjwatson2786/SRT-Audio/issues/2#issuecomment-1084997683_

**Comment by magnusjwatson2786** [comment]
I m using python version 3.9.6 and the code runs flawlessly for me with following packages installed: 

- comtypes==1.1.10
- pydub==0.25.1
- pypiwin32==223
- pyttsx3==2.90
- pywin32==301

https://i.e-z.host/64b400d9.png -> my env setup

Ypu might get a fix for the importError here : https://stackoverflow.com/questions/65573140/importerror-no-system-module-pywintypes-pywintypes39-dll

**Comment by faveoled** [comment]
Fails on Linux:
```
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from versions: none)
ERROR: No matching distribution found for pywin32==301
```
