### ISSUE TITLE
Fails on Linux:

### ISSUE THREAD

**Issue by magnusjwatson2786** [magnusjwatson2786/SRT-Audio#4]
Fails on Linux:
```
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from versions: none)
ERROR: No matching distribution found for pywin32==301
```

_Originally posted by @faveoled in https://github.com/magnusjwatson2786/SRT-Audio/issues/3#issuecomment-1898442316_

**Comment by magnusjwatson2786** [comment]
Hi, i updated the _requirements.txt_ so that it only attempts to install _pywin32_ and _pypiwin32_ only on **Windows** platform. 
It is just a debug attempt, i **haven't** tested it to see if it works, as i dont have access to a linux machine/os. 

Please try the install again and inform me about the results. (Even if it works, please inform)

**Comment by faveoled** [comment]
Installation works. Running tts.py seems to have modified **speech1** directory, numbered files have sound in it but **full.wav** is silent.
UPD: Not silent, works well

**Comment by magnusjwatson2786** [comment]
Glad it worked!
Feel free to suggest any modifications in future.
